apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-fiap-order-application-ms
  labels:
    app: soat-fiap-order-application-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat-fiap-order-application-ms
  template:
    metadata:
      labels:
        app: soat-fiap-order-application-ms
    spec:
      containers:
        - name: soat-fiap-order-application-ms
          image: 590422439565.dkr.ecr.us-east-1.amazonaws.com/soat-fiap-order-application-ms:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-order-application-ms-configmap
                  key: AWS_REGION
            - name: COSTUMER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-order-application-ms-configmap
                  key: COSTUMER_BASE_URL
            - name: PRODUCT_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-order-application-ms-configmap
                  key: PRODUCT_BASE_URL
          resources:
            requests:
              memory: "62Mi"
              cpu: "250m"
            limits:
              memory: "124Mi"
              cpu: "500m"
